// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkwqwprlrfzgjvklmtvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrd3F3cHJscmZ6Z2p2a2xtdHZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzYyNTUsImV4cCI6MjA2MDExMjI1NX0._1rjcq1C0FvLWoMRbTWB9jxQryap7Ik7WZfDxz0yhYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);